apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daughter-app-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: applications/daughter-app-1
    repoURL: https://github.com/trawler/argocd-mother-of-all
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
